### ISSUE TITLE
Description clarity

### ISSUE THREAD

**Issue by be-great** [Emmo00/alxcheck#2]
Interesting tool you have built :).  But basically, it's only for the  alx-system-engineering-DevOps
section If you can add this to the description it will be more clear to understand what the tool is exactly for  🙌.

**Comment by Emmo00** [comment]
@be-great . It's actually for more than that. The README file explains what it does and its present features.

It works for C, Python, JavaScript projects.

**Comment by be-great** [comment]
Oh that is great let me check it 🙌

**Comment by be-great** [comment]
It will be great if you add a feature that auto-creates files of function prototypes present on the main. h to reduce the duration of creating files.

**Comment by Emmo00** [comment]
@be-great 

That sounds interesting, but it's kinda out of the scope of this project

Although, I'd be willing to work on a project like that together

**Comment by be-great** [comment]
Sound Good. 🙌

**Comment by be-great** [comment]
Do you have a flowchart of how the code work 
And the purpose of each file you created?!

**Comment by Emmo00** [comment]
@be-great Not really, but I can give a high level explanatory 👇🏻:

The entry point of the program is the `main()` function in the `alxcheck/main.py` file. There I imported all the checks from `alxcheck/checks/__init__.py`.

In the `main()` function, I called the checks for `README.md` in the cwd ( current working directory), then went on the call checks based on file type (e g, `.py` or `.js`).

**Comment by be-great** [comment]
OK thank you.  🙏🏽
