### ISSUE TITLE
Improve detection of python virtual environment folder

### ISSUE THREAD

**Issue by adobki** [Emmo00/alxcheck#4]
The logic for detecting Python virtual environment folders needs to be improved. Your implementation assumes that the folder would simply be named either `venv` or `env`, but that is not always the case. Python places no restrictions on the folder name, so most documentations/guides on the internet suggest using a custom name, which means that a Python virtual environment folder can actually be named anything at all, e.g. `alxcheck_venv` or `_python_bin`. I name mine `.venv` for instance, so that it stays at the top of the list in a directory listing, with the added advantage of being hidden and ignored by most apps in UNIX.

However, regardless of what the folder is named, it always has a `./pyvenv.cfg` file in it _(see attached screenshot)_, so perhaps have your script look for that file instead, or a similar artefact that applies to all virtual environment folders.

![image](https://github.com/Emmo00/alxcheck/assets/95923018/bb1cac3e-aaae-4661-b8a6-4dda3e56192a)
_Source: [official documentation](https://docs.python.org/3/library/venv.html#creating-virtual-environments:~:text=and%20places%20a-,pyvenv.cfg,-file%20in%20it)_

**Comment by Emmo00** [comment]
Thanks @adobki for this...
