### ISSUE TITLE
Ignore __init__.py file if it is empty

### ISSUE THREAD

**Issue by adobki** [Emmo00/alxcheck#5]
Python requires modules to have a `__init__.py` file, even if the file is left empty. `alxcheck` needs to skip checking this file if it is empty.

![image](https://github.com/Emmo00/alxcheck/assets/95923018/1a66b016-7e29-4e62-888a-8b46e47a9a03)

**Comment by Emmo00** [comment]
Nice one @adobki ... I'd improve that

**Comment by samdoghor** [comment]
Anyone working on this?

**Comment by Emmo00** [comment]
Go ahead @samdoghor

**Comment by adobki** [comment]
> Anyone working on this?

I was gonna, but alright then. Go ahead. #happyCoding 💪
