### ISSUE TITLE
JavaScript shebang and executable tests should be for only node.js/executable JavaScript files

### ISSUE THREAD

**Issue by adobki** [Emmo00/alxcheck#6]
Only node.js/executable JavaScript files need a shebang. Scripts that would be loaded by HTML do not typically have one, nor are they executable as that could actually lead to issues.

`alxcheck` needs to find a way to detect this, or perhaps display these messages as _**warnings** (orange/amber)_ as opposed to _**errors** (red)_ and a notice to the user to only fix those if they are node.js executable scripts.

![image](https://github.com/Emmo00/alxcheck/assets/95923018/1536b62a-7385-4caf-8ad5-dc02392bd8d8)

**Comment by Emmo00** [comment]
🤔
It'd be quite challenging to differentiate browser files from nodejs files tho

**Comment by adobki** [comment]
> 🤔 It'd be quite challenging to differentiate browser files from nodejs files tho

Yeah, bro. Which is why I suggested using a warning instead. 😅
You could simply make it a warning for now until you figure out how to differentiate them.

**Comment by adobki** [comment]
> 🤔 It'd be quite challenging to differentiate browser files from nodejs files tho

Yeah, bro. Which is why I suggested using a warning instead. 😅
You could simply make it a warning with a notice for now, until you figure out how to differentiate them. You don't wanna have people erroneously adding shebangs and executable flags to scripts that have no business having 'em.

**Comment by Emmo00** [comment]
Ohk... Makes sense
